
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mercadosoluciones
 */
public class Divisas extends javax.swing.JFrame {

    /**
     * Creates new form Divisas
     */
    public Divisas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox<>();
        ComboBox2 = new javax.swing.JComboBox<>();
        txtEntrada = new javax.swing.JTextField();
        txtSalida = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Divisas");

        jLabel1.setText("CONVERSOR DE MONEDAS");

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARS (Pesos Argentinos)", "USD (Dolar Estado Unidense)", "EUR (Euro)", "GBP (Libas Esterlinas)", "JPY (Yen Japones)", "KRW (Won Sul-Coreano)" }));

        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD (Dolar Estado Unidense)", "EUR (Euro)", "GBP (Libras Esterlinas)", "JPY (Yen Japones)", "KRW (Won Sul-Coreano)", "ARS (Pesos Argentinos)" }));

        txtEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEntradaKeyTyped(evt);
            }
        });

        txtSalida.setEditable(false);

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        btnConvertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnConvertirKeyTyped(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConvertir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(btnLimpiar))
                            .addComponent(txtEntrada)
                            .addComponent(txtSalida))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvertir)
                    .addComponent(btnLimpiar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAtras))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        String box1 = (String)ComboBox1.getSelectedItem();
        String box2 = (String)ComboBox2.getSelectedItem();
        
        if(box1.equals("ARS (Pesos Argentinos)") && box2.equals("USD (Dolar Estado Unidense)"))
        {
            double ars = Double.parseDouble(txtEntrada.getText());
            
            double usd = (double)(ars * 0.0052);
            txtSalida.setText(String.valueOf(usd));
        }
        else if(box1.equals("ARS (Pesos Argentinos)") && box2.equals("EUR (Euro)"))
        {
            double ars = Double.parseDouble(txtEntrada.getText());
            
            double eur = (double)(ars * 0.0049);
            txtSalida.setText(String.valueOf(eur));
        }
        else if(box1.equals("ARS (Pesos Argentinos)") && box2.equals("GBP (Libas Esterlinas)"))
        {
            double ars = Double.parseDouble(txtEntrada.getText());
            
            double gbp = (double)(ars * 0.0044);
            txtSalida.setText(String.valueOf(gbp));
        }
        else if(box1.equals("ARS (Pesos Argentinos)") && box2.equals("JPY (Yen Japones)"))
        {
            double ars = Double.parseDouble(txtEntrada.getText());
            
            double jpy = (double)(ars * 0.69);
            txtSalida.setText(String.valueOf(jpy));
        }
        else if(box1.equals("ARS (Pesos Argentinos)") && box2.equals("KRW (Won Sul-Coreano)"))
        {
            double ars = Double.parseDouble(txtEntrada.getText());
            
            double krw = (double)(ars * 6.65);
            txtSalida.setText(String.valueOf(krw));
        }
        else if(box1.equals("ARS (Pesos Argentinos)") && box2.equals("ARS (Pesos Argentinos)"))
       {
           double ars = Double.parseDouble(txtEntrada.getText());
         
           txtSalida.setText(String.valueOf(ars));
       }
        
        
        if (box1.equals("USD (Dolar Estado Unidense)") && box2.equals("EUR (Euro)"))
        {
            double usd = Double.parseDouble(txtEntrada.getText());
            
            double eur = (double)(usd * 0.93);
            txtSalida.setText(String.valueOf(eur));
        }
        else if (box1.equals("USD (Dolar Estado Unidense)") && box2.equals("GBP (Libras Esterlinas)"))
        {
            double usd = Double.parseDouble(txtEntrada.getText());
            
            double gbp = (double)(usd * 0.83);
            txtSalida.setText(String.valueOf(gbp));
        }
        else if (box1.equals("USD (Dolar Estado Unidense)") && box2.equals("JPY (Yen Japones)"))
        {
            double usd = Double.parseDouble(txtEntrada.getText());
            
            double jpy = (double)(usd * 131.30);
            txtSalida.setText(String.valueOf(jpy));
        }
        else if (box1.equals("USD (Dolar Estado Unidense)") && box2.equals("KRW (Won Sul-Coreano)"))
        {
            double usd = Double.parseDouble(txtEntrada.getText());
            
            double krw = (double)(usd * 1267.97);
            txtSalida.setText(String.valueOf(krw));
        }
        else if (box1.equals("USD (Dolar Estado Unidense)") && box2.equals("ARS (Pesos Argentinos)"))
        {
            double usd = Double.parseDouble(txtEntrada.getText());
            
            double ars = (double)(usd * 377);
            txtSalida.setText(String.valueOf(ars));
        }
        else if(box1.equals("USD (Dolar Estado Unidense)") && box2.equals("USD (Dolar Estado Unidense)"))
       {
           double usd = Double.parseDouble(txtEntrada.getText());
         
           txtSalida.setText(String.valueOf(usd));
       }
        
        
        
        if (box1.equals("EUR (Euro)") && box2.equals("USD (Dolar Estado Unidense)"))
        {
            double eur = Double.parseDouble(txtEntrada.getText());
            
            double usd = (double)(eur * 1.07);
            txtSalida.setText(String.valueOf(usd));
        }
        else if (box1.equals("EUR (Euro)") && box2.equals("GBP (Libas Esterlinas)"))
        {
            double eur = Double.parseDouble(txtEntrada.getText());
            
            double gbp = (double)(eur * 0.89);
            txtSalida.setText(String.valueOf(gbp));
        }
        else if (box1.equals("EUR (Euro)") && box2.equals("JPY (Yen Japones)"))
        {
            double eur = Double.parseDouble(txtEntrada.getText());
            
            double jpy = (double)(eur * 140.64);
            txtSalida.setText(String.valueOf(jpy));
        }
        else if (box1.equals("EUR (Euro)") && box2.equals("KRW (Won Sul-Coreano)"))
        {
            double eur = Double.parseDouble(txtEntrada.getText());
            
            double krw = (double)(eur * 1353.56);
            txtSalida.setText(String.valueOf(krw));
        }
        else if (box1.equals("EUR (Euro)") && box2.equals("ARS (Pesos Argentinos)"))
        {
            double eur = Double.parseDouble(txtEntrada.getText());
            
            double ars = (double)(eur * 203.43);
            txtSalida.setText(String.valueOf(ars));
        }
        else if(box1.equals("EUR (Euro)") && box2.equals("EUR (Euro)"))
        {
           double eur = Double.parseDouble(txtEntrada.getText());
         
           txtSalida.setText(String.valueOf(eur));
        }
        
        
        if(box1.equals("GBP (Libas Esterlinas)") && box2.equals("USD (Dolar Estado Unidense)"))
        {
            double gbp = Double.parseDouble(txtEntrada.getText());
            
            double usd = (double)(gbp * 1.21);
            txtSalida.setText(String.valueOf(usd));
        }
        else if(box1.equals("GBP (Libas Esterlinas)") && box2.equals("EUR (Euro)"))
        {
            double gbp = Double.parseDouble(txtEntrada.getText());
            
            double eur = (double)(gbp * 1.13);
            txtSalida.setText(String.valueOf(eur));
        }
        else if(box1.equals("GBP (Libas Esterlinas)") && box2.equals("JPY (Yen Japones)"))
        {
            double gbp = Double.parseDouble(txtEntrada.getText());
            
            double jpy = (double)(gbp * 158.41);
            txtSalida.setText(String.valueOf(jpy));
        }
        else if(box1.equals("GBP (Libas Esterlinas)") && box2.equals("KRW (Won Sul-Coreano)"))
        {
            double gbp = Double.parseDouble(txtEntrada.getText());
            
            double krw = (double)(gbp * 1529.80);
            txtSalida.setText(String.valueOf(krw));
        }
        else if(box1.equals("GBP (Libas Esterlinas)") && box2.equals("ARS (Pesos Argentinos)"))
        {
            double gbp = Double.parseDouble(txtEntrada.getText());
            
            double ars = (double)(gbp * 229.71);
            txtSalida.setText(String.valueOf(ars));
        }
        else if(box1.equals("GBP (Libas Esterlinas)") && box2.equals("GBP (Libas Esterlinas)"))
        {
           double gbp = Double.parseDouble(txtEntrada.getText());
         
           txtSalida.setText(String.valueOf(gbp));
        }
        
        
        if (box1.equals("JPY (Yen Japones)") && box2.equals("USD (Dolar Estado unidense)"))
        {
            double jpy = Double.parseDouble(txtEntrada.getText());
            
            double usd = (double)(jpy * 0.0076);
            txtSalida.setText(String.valueOf(usd));
        }
        else if (box1.equals("JPY (Yen Japones)") && box2.equals("EUR (Euro)"))
        {
            double jpy = Double.parseDouble(txtEntrada.getText());
            
            double eur = (double)(jpy * 0.0071);
            txtSalida.setText(String.valueOf(eur));
        }
        else if (box1.equals("JPY (Yen Japones)") && box2.equals("GBP (Libas Esterlinas)"))
        {
            double jpy = Double.parseDouble(txtEntrada.getText());
            
            double gbp = (double)(jpy * 0.0063);
            txtSalida.setText(String.valueOf(gbp));
        }
        else if (box1.equals("JPY (Yen Japones)") && box2.equals("KRW (Won Sul-Coreano)"))
        {
            double jpy = Double.parseDouble(txtEntrada.getText());
            
            double krw = (double)(jpy * 9.65);
            txtSalida.setText(String.valueOf(krw));
        }
        else if (box1.equals("JPY (Yen Japones)") && box2.equals("ARS (Pesos Argentinos)"))
        {
            double jpy = Double.parseDouble(txtEntrada.getText());
            
            double ars = (double)(jpy * 1.45);
            txtSalida.setText(String.valueOf(ars));
        }
        else if(box1.equals("JPY (Yen Japones)") && box2.equals("JPY (Yen Japones)"))
        {
           double jpy = Double.parseDouble(txtEntrada.getText());
         
           txtSalida.setText(String.valueOf(jpy));
        }
        
        
        if (box1.equals("KRW (Won Sul-Coreano)") && box2.equals("USD (Dolar Estado Unidense)"))
        {
            double krw = Double.parseDouble(txtEntrada.getText());
            
            double usd = (double)(krw * 0.00079);
            txtSalida.setText(String.valueOf(usd));
        }
        else if (box1.equals("KRW (Won Sul-Coreano)") && box2.equals("EUR (Euro)"))
        {
            double krw = Double.parseDouble(txtEntrada.getText());
            
            double eur = (double)(krw * 0.00074);
            txtSalida.setText(String.valueOf(eur));
        }
        else if (box1.equals("KRW (Won Sul-Coreano)") && box2.equals("GBP (Libas Esterlinas)"))
        {
            double krw = Double.parseDouble(txtEntrada.getText());
            
            double gbp = (double)(krw * 0.00065);
            txtSalida.setText(String.valueOf(gbp));
        }
        else if (box1.equals("KRW (Won Sul-Coreano)") && box2.equals("JPY (Yen Japones)"))
        {
            double krw = Double.parseDouble(txtEntrada.getText());
            
            double jpy = (double)(krw * 0.10);
            txtSalida.setText(String.valueOf(jpy));
        }
        else if (box1.equals("KRW (Won Sul-Coreano)") && box2.equals("ARS (Pesos Argentinos)"))
        {
            double krw = Double.parseDouble(txtEntrada.getText());
            
            double ars = (double)(krw * 0.15);
            txtSalida.setText(String.valueOf(ars));
        }
        else if(box1.equals("KRW (Won Sul-Coreano)") && box2.equals("KRW (Won Sul-Coreano)"))
        {
           double krw = Double.parseDouble(txtEntrada.getText());
         
           txtSalida.setText(String.valueOf(krw));
        }

    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtEntrada.setText("");
        txtSalida.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        Menu abrir = new Menu();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnConvertirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConvertirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertirKeyTyped

    private void txtEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntradaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros por favor.");
        }
    }//GEN-LAST:event_txtEntradaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Divisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Divisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
